language: rust
cache: cargo
os: linux
sudo: true

branches:
  only:
    - master

rust:
  - 1.31.0
  - stable

env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-D warnings"

install:
  - sudo apt-get install rpm librpm-dev
  - sudo rpm --initdb
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo fmt --all -- --check
  #- cargo clippy --all # TODO: clippy
  - cargo build --no-default-features --release
  - cargo test --no-default-features --release
  - cargo doc --no-deps
