name: Compile and run tests

on: [push, pull_request]

jobs:
  lint:
    container: "registry.fedoraproject.org/fedora:latest"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install librpm dependencies
        run: |
          dnf install -y rpm-devel gcc clang-devel

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            components: clippy, rustfmt
            override: true

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -vv --all -- --check

      - uses: actions-rs/cargo@v1
        with:
          command: doc
          args: -vv --no-deps

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  run_tests:
    strategy:
      matrix:
        container: ["registry.fedoraproject.org/fedora:latest", "quay.io/centos/centos:stream9"]
    container: ${{ matrix.container }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install librpm dependencies
        run: |
          dnf install -y rpm-devel gcc clang-devel
          dnf -y clean all

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: -vv --release --all-features
