name: Compile and run tests

on: [push, pull_request]

jobs:
<<<<<<< HEAD
  lint-and-build:
=======
  list-and-build:
>>>>>>> 2e691f4 (Installing Rust myself in the containers as other approaches doesn't seem to work)
    runs-on: ubuntu-latest
    container: "quay.io/centos/centos:stream9"

    steps:
      - uses: actions/checkout@v2

      - name: 📦 Install librpm dependencies
        run: |
          dnf install -y rpm-devel gcc clang-devel rustc cargo clippy rustfmt
          dnf -y clean all

      - name: 📎 Run Linters
        run: |
          cargo clippy --release -- -D warnings
          cargo fmt --all -- --check
          cargo doc --no-deps

      - name: 🔨 Build (Debug)
        run: cargo build --verbose

      - name: 🔨 Build (Release)
        run: cargo build --release --verbose

      - name: 🧪 Run Unit Tests
        run: cargo test --release --bins --lib

  integration-tests:
    strategy:
      matrix:
        container: ["registry.fedoraproject.org/fedora:38", "quay.io/centos/centos:stream9"]
    container: ${{ matrix.container }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 📦 Install librpm dependencies
        run: |
          dnf install -y rpm-devel gcc clang-devel rustc cargo clippy rustfmt
          dnf -y clean all

      - name: 🧪 Run Integration Tests
        run: |
          cargo test --test '*' --release --all-features
